import Footer from "@/components/shared/Footer";
import Navbar from "@/components/shared/Navbar";
import WorkoutProvider from "@/Context/WorkoutContext";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fit Log",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="bg-black min-h-full flex flex-col" data-theme="dark">
        <WorkoutProvider>
          <Navbar />
          {children}
          <Footer />
        </WorkoutProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
